version: "3.9"
services:
  meimad2-nginx:
    image: meimad2-nginx-img
    build:
      context: ../Meimad2Nginx
      dockerfile: .DockerFile
    ports:
    - "4020:80"
    - "80:80"

  igi-react-cesium:
    image:           igi-react-cesium-client-img
    container_name: "igi-react-cesium-client-cont"
    build:
      context: ../igi-react-cesium
      dockerfile: .Dockerfile
    ports:
      - "4008:4008"
#      - "80:4008"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

  meimad2-server:
    image:           meimad2-server-img
    container_name: "meimad2-server-cont"
    build:
      context: ../Meimad2Server
      dockerfile: .Dockerfile
    ports:
      - "9004:9004"

#  simplex-postgres:
#    image: geographica/postgis:unbiased_uakari
#    ports:
#        - "5432:5432"
#    volumes:
#      - db-data:/data
#    environment:
#      - POSTGRES_PASSWD=postgres
    # image:           simplex-postgres-img
#    container_name: "simplex-postgres-cont"
