PACK_DEST_DIR_PARENT = "d:/temp/1"
PACK_SHORT_DIR_NAME = "meimad-docker-compose-pack2"
PACK_DEST_DIR_FULL_FILE_NAME = f'{PACK_DEST_DIR_PARENT}/{PACK_SHORT_DIR_NAME}'


UBUNTU_DEV_EXTERNAL_IP = '83.229.74.11'
UBUNTU_DEV_INTERNAL_IP = '172.16.0.20'

DEV_SERVER_EXTERNAL_IP = '5.100.249.96'
DEV_SERVER_INTERNAL_IP = '172.16.0.5'

PROFILE_NAME__UBUNTU_LOCAL_DEV = "ubuntu-local-dev"
PROFILE_NAME__UBUNTU_SIMPLEX_DEV = "ubuntu-simplex-dev"

PROFILE_NAME__AWS = "aws"
